Domain\Model\User\User:
    type: entity
    table: user
    embedded:
        id:
            class: Domain\Model\User\UserId
    fields:
        email:
            type: string
            length: 150
        twitterAccount:
            type: string
            length: 50
        createdAt:
            type: datetime
        updatedAt:
            type: datetime