services:

    #Application services
    application_service_user_signup:
        class: Application\Service\User\SignUpUserService
        arguments: ["@doctrine_repository_user"]

    #Repositories
    doctrine_repository_user:
        class: InfrastructureBundle\Repository\User\DoctrineUserRepository
        arguments: ["@doctrine.orm.entity_manager"]