services:

    #CommandHandler
    command_handler:
        class: Application\Command\CommandHandler

    #Application UseCase
    application_usecase_user_signup:
        class: Application\UseCase\User\SignUpUserUseCase
        arguments: ["@doctrine_repository_user"]
        tags:
            - { name: use_case }

    #Repositories
    doctrine_repository_user:
        class: InfrastructureBundle\Repository\User\DoctrineUserRepository
        arguments: ["@doctrine.orm.entity_manager"]